version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install cfn-lint
  build:
    commands:
      - echo "Running cfn-lint on template.yml"
      - cfn-lint template.yml
artifacts:
  files:
    - "**/*"
 
 