AWSTemplateFormatVersion: 2010-09-09
Description: Insecure CloudFormation template for testing security scanners

Resources:
  InsecureEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b09ffb6d8b58ca91
      InstanceType: t2.micro
      KeyName: my-insecure-key
      SecurityGroups:
        - !Ref InsecureSecurityGroup

  InsecureSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all inbound traffic
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  InsecureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: insecure-bucket-example
      AccessControl: PublicRead
 

 